### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by dimpase** [sagemath/publications#7]
I get

    $ make
        python pubparse.py sage
        ... sage
        Traceback (most recent call last): File "pubparse.py", line 1104, in <module>
        db = process_database(publications_general)
        File "pubparse.py", line 840, in process_database  bibdb = parser.parse_file(dbfilename)
         File "/users/dimpase/.local/lib/python2.7/site-packages/pybtex/database/input/__init__.py", line 51, in parse_file
         self.parse_stream(f)
         File "/users/dimpase/.local/lib/python2.7/site-packages/pybtex/database/input/bibtex.py", line 365, in parse_stream
         for entry in entry_iterator:
         File "/users/dimpase/.local/lib/python2.7/site-packages/pybtex/database/input/bibtex.py", line   178, in parse_bibliography
         self.handle_error(error)
         File "/users/dimpase/.local/lib/python2.7/site-packages/pybtex/database/input/bibtex.py", line 350, in handle_error
         report_error(error)
         File "/users/dimpase/.local/lib/python2.7/site-packages/pybtex/errors.py", line 78, in    report_error
        raise exception
        pybtex.scanner.TokenRequired: '}' expected
        make: *** [publications-general.html] Error 1

**Comment by haraldschilly** [comment]
It works for me and on the server; which means, that the website already updated with your publications. I assume your pybtex is an old one and it chokes on one of the special characters or something like that.

**Comment by haraldschilly** [comment]
Ok, what an irony. I have an old one and now a problem after updating.

**Comment by dimpase** [comment]
It is not my commit to blame, it also did not work for me before my update.

**Comment by haraldschilly** [comment]
Yes, I was referring to the python package. It works for an older version but not the new one. So, well, it's time to hunt a sneaky syntax error :mag:

**Comment by dimpase** [comment]
it's missing ',' in the main .bib, line 4170.
You'll get a pull request in a moment

**Comment by haraldschilly** [comment]
I just pushed
